# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-peso
  template:
    metadata:
      labels:
        app: web-peso
    spec:
      containers:
        - name: container-app
          image: felippedeiro/conversao-peso:v1
          ports:
            - containerPort: 80
---
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  selector:
    app: web-peso
  ports:
    - port: 80 
      targetPort: 80
      nodePort: 30000
  type: NodePort